/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkersRouteImport } from './routes/workers'
import { Route as HomeownersRouteImport } from './routes/homeowners'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as AgenciesRouteImport } from './routes/agencies'
import { Route as IndexRouteImport } from './routes/index'

const WorkersRoute = WorkersRouteImport.update({
  id: '/workers',
  path: '/workers',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeownersRoute = HomeownersRouteImport.update({
  id: '/homeowners',
  path: '/homeowners',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const AgenciesRoute = AgenciesRouteImport.update({
  id: '/agencies',
  path: '/agencies',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agencies': typeof AgenciesRoute
  '/agents': typeof AgentsRoute
  '/homeowners': typeof HomeownersRoute
  '/workers': typeof WorkersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agencies': typeof AgenciesRoute
  '/agents': typeof AgentsRoute
  '/homeowners': typeof HomeownersRoute
  '/workers': typeof WorkersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agencies': typeof AgenciesRoute
  '/agents': typeof AgentsRoute
  '/homeowners': typeof HomeownersRoute
  '/workers': typeof WorkersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/agencies' | '/agents' | '/homeowners' | '/workers'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/agencies' | '/agents' | '/homeowners' | '/workers'
  id: '__root__' | '/' | '/agencies' | '/agents' | '/homeowners' | '/workers'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgenciesRoute: typeof AgenciesRoute
  AgentsRoute: typeof AgentsRoute
  HomeownersRoute: typeof HomeownersRoute
  WorkersRoute: typeof WorkersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workers': {
      id: '/workers'
      path: '/workers'
      fullPath: '/workers'
      preLoaderRoute: typeof WorkersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/homeowners': {
      id: '/homeowners'
      path: '/homeowners'
      fullPath: '/homeowners'
      preLoaderRoute: typeof HomeownersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agencies': {
      id: '/agencies'
      path: '/agencies'
      fullPath: '/agencies'
      preLoaderRoute: typeof AgenciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgenciesRoute: AgenciesRoute,
  AgentsRoute: AgentsRoute,
  HomeownersRoute: HomeownersRoute,
  WorkersRoute: WorkersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
